### ISSUE TITLE
Hardcoded path on LDTRenderFilters.grf

### ISSUE THREAD

**Issue by abelvargas** [ezequielmastrasso/gaffer-examples#17]
Hi there, while installing the examples, my team found that there's a path on line 150 of LDTRenderFilters.grf that is not using the Env Variables. This was giving errors on opening up the scene files.

Thank you

**Comment by ezequielmastrasso** [comment]
Thanks for reporting this!
keep me posted if anything

Eze

**Comment by abelvargas** [comment]
Hey Ezequiel, on that same note. Some of the render paths inside the boxes in LDTGaffer-examples are pointing to a local folder as well. Might be good to get those online. It's not a deal breaker though :)
